const dreamTagSuggestions = [
  { id: 1, name: "Adventure", label: "Adventure", value: "adventure" },
  { id: 2, name: "Imagination", label: "Imagination", value: "imagination" },
  {
    id: 3,
    name: "Lucid Dreaming",
    label: "Lucid Dreaming",
    value: "lucid-dreaming",
  },
  { id: 4, name: "Nightmares", label: "Nightmares", value: "nightmares" },
  {
    id: 5,
    name: "Recurring Dreams",
    label: "Recurring Dreams",
    value: "recurring-dreams",
  },
  { id: 6, name: "Surreal", label: "Surreal", value: "surreal" },
  { id: 7, name: "Prophetic", label: "Prophetic", value: "prophetic" },
  { id: 8, name: "Emotions", label: "Emotions", value: "emotions" },
  {
    id: 9,
    name: "Relationships",
    label: "Relationships",
    value: "relationships",
  },
  { id: 10, name: "Stress", label: "Stress", value: "stress" },
  { id: 11, name: "Travel", label: "Travel", value: "travel" },
  { id: 12, name: "Nature", label: "Nature", value: "nature" },
  {
    id: 13,
    name: "Spirituality",
    label: "Spirituality",
    value: "spirituality",
  },
  { id: 14, name: "Memories", label: "Memories", value: "memories" },
  { id: 15, name: "Creativity", label: "Creativity", value: "creativity" },
  { id: 16, name: "Action", label: "Action", value: "action" },
  { id: 17, name: "Horror", label: "Horror", value: "horror" },
  { id: 18, name: "Mystery", label: "Mystery", value: "mystery" },
  { id: 19, name: "Comedy", label: "Comedy", value: "comedy" },
  { id: 20, name: "Drama", label: "Drama", value: "drama" },
  { id: 21, name: "Fantasy", label: "Fantasy", value: "fantasy" },
  { id: 22, name: "Sci-Fi", label: "Sci-Fi", value: "sci-fi" },
  { id: 23, name: "Thriller", label: "Thriller", value: "thriller" },
  { id: 24, name: "Romance", label: "Romance", value: "romance" },
  { id: 25, name: "History", label: "History", value: "history" },
  { id: 26, name: "Biography", label: "Biography", value: "biography" },
  { id: 27, name: "Documentary", label: "Documentary", value: "documentary" },
  { id: 28, name: "Crime", label: "Crime", value: "crime" },
  { id: 29, name: "Animation", label: "Animation", value: "animation" },
  { id: 30, name: "Family", label: "Family", value: "family" },
  { id: 31, name: "Music", label: "Music", value: "music" },
  { id: 32, name: "Sport", label: "Sport", value: "sport" },
  { id: 33, name: "War", label: "War", value: "war" },
  { id: 34, name: "Western", label: "Western", value: "western" },
  { id: 35, name: "Musical", label: "Musical", value: "musical" },
  {
    id: 36,
    name: "Supernatural",
    label: "Supernatural",
    value: "supernatural",
  },
];

export default dreamTagSuggestions;
